Repository geosolutions-it/clevmetro-nfd, pull requests merged in 2018-02, with the labels that each got.

#153 management form is now the last
  .gitignore
  nfdapi/nfdcore/formdefinitions.py
Labels: In Test, in progress, pending review, review

#152 Closes #90, Closes #106, Closes #104
  nfdclient/js/actions/exportfeatures.js
  nfdclient/js/api/naturalfeaturesdata.js
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.jsx
  nfdclient/js/epics/exportfeatures.js
  nfdclient/js/plugins/ViewEditNaturalFeatures.jsx
  nfdclient/js/plugins/featuretypes/Animal.jsx
  nfdclient/js/plugins/featuretypes/Fungus.jsx
  nfdclient/js/plugins/featuretypes/NaturalArea.jsx
  nfdclient/js/plugins/featuretypes/Plant.jsx
  nfdclient/js/plugins/featuretypes/Slimemold.jsx
  nfdclient/js/reducers/exportfeatures.js
Labels: in progress, pending review, review

#150 Added notes for each tab on the backend
  nfdapi/nfdcore/migrations/0014_note.py
  nfdapi/nfdcore/migrations/0015_auto_20180207_1736.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
Labels: In Test, in progress, pending review, review

#155 added textarea as a type for the notes
  nfdapi/nfdcore/nfdserializers.py
Labels: In Test, pending review, review

#156 Closes #138
  nfdclient/js/plugins.js
  nfdclient/js/plugins/AddNaturalFeatures.jsx
  nfdclient/js/plugins/FeatureTypeReportMenu.jsx
  nfdclient/js/plugins/FeaturesPlugin.jsx
  nfdclient/js/plugins/NFDTutorial.jsx
  nfdclient/js/plugins/NfdLogin.jsx
  nfdclient/js/plugins/ToggleAddEditPanel.jsx
  nfdclient/localConfig.json
Labels: in progress, pending review, review

#154 Closes #127
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.css
  nfdclient/js/components/naturalfeatures/Fields/TextField.jsx
  nfdclient/js/components/naturalfeatures/Fields/index.js
Labels: in progress, pending review, review

#158 fixed duplicate form fields for notes on management tab
  nfdapi/nfdcore/nfdserializers.py
Labels: In Test, pending review, review

#159 fixed broken add occurrence flow
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#160 Closes #147
  nfdclient/js/api/naturalfeaturesdata.js
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.jsx
  nfdclient/js/components/naturalfeatures/Fields/NumericField.jsx
  nfdclient/js/epics/naturalfeatures.js
  nfdclient/js/ms2Override/LeafletDrawSupport.jsx
  nfdclient/js/reducers/naturalfeatures.js
Labels: in progress, pending review, review

#161 Add multiple selection to most dict models
  nfdapi/nfdcore/migrations/0016_auto_20180212_1549.py
  nfdapi/nfdcore/migrations/0017_auto_20180212_1550.py
  nfdapi/nfdcore/migrations/0018_auto_20180212_1635.py
  nfdapi/nfdcore/migrations/0019_auto_20180212_1635.py
  nfdapi/nfdcore/migrations/0020_jsonfield_20180213_1422.py
  nfdapi/nfdcore/migrations/0021_jsonfield_20180213_1601.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
Labels: In Test, in progress, pending review, review

#162 changed name of the observation tab
  nfdapi/nfdcore/formdefinitions.py
Labels: In Test, in progress, pending review, review

#163 Issue#115
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.css
  nfdclient/js/components/naturalfeatures/Fields/SelectField.jsx
Labels: in progress, pending review, review

#165 fixed incorrect form definition
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#166 Fixes
  nfdclient/js/components/naturalfeatures/Fields/SelectField.jsx
  nfdclient/js/components/naturalfeatures/Fields/index.js
Labels: in progress, pending review, review

#167 fixed bug with the rename of the observer tab
  nfdapi/nfdcore/formdefinitions.py
Labels: in progress, pending review, review

#169 Fixed animal highlight icon and Observer icon
  nfdclient/config.json
  nfdclient/js/utils/nfdUtils.js
Labels: in progress, pending review, review

#170 added show_key_with_value field to featuretypes forms
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#171 Closes #148
  nfdclient/js/components/naturalfeatures/Fields/SelectField.jsx
  nfdclient/js/utils/nfdUtils.js
Labels: in progress, pending review, review

#168 renamed to Observer on the other featuretypes
  nfdapi/nfdcore/formdefinitions.py
Labels: in progress, pending review, review

#173 close #112
  nfdclient/assets/translations/data.en-US
  nfdclient/js/plugins/AddNaturalFeatures.jsx
  nfdclient/js/plugins/FeatureTypeReportMenu.jsx
  nfdclient/js/plugins/FeaturesPlugin.jsx
  nfdclient/js/plugins/ToggleAddEditPanel.jsx
  nfdclient/js/plugins/login/index.js
Labels: in progress, pending review, review

#172 Closes #157 added clevmetro maps
  nfdclient/config.json
  nfdclient/js/app.jsx
  nfdclient/js/ms2Override/ClevMetroLayer.js
Labels: in progress, pending review, review

#174 stringcombo fields are saved correctly
  nfdapi/nfdcore/nfdserializers.py
Labels: In Test, pending review, review

#178 Closes #105 Added permalink supporting feature version
  nfdclient/js/actions/exportfeatures.js
  nfdclient/js/actions/naturalfeatures.js
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.jsx
  nfdclient/js/epics/exportfeatures.js
  nfdclient/js/epics/naturalfeatures.js
  nfdclient/js/plugins/ViewEditNaturalFeatures.jsx
Labels: in progress, pending review, review

#179 Closes #114 improved tutorial
  nfdclient/localConfig.json
Labels: in progress, pending review, review

#180 refactored form definitions
  nfdapi/nfdapi/settings.py
  nfdapi/nfdapi/urls.py
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/form_definitions/conifer-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fern-plant-forms.yml
  nfdapi/nfdcore/form_definitions/flowering-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fungus-forms.yml
  nfdapi/nfdcore/form_definitions/land-animal-forms.yml
  nfdapi/nfdcore/form_definitions/moss-forms.yml
  nfdapi/nfdcore/form_definitions/natural-area-forms.yml
  nfdapi/nfdcore/form_definitions/pond-lake-animal-forms.yml
  nfdapi/nfdcore/form_definitions/slimemold-forms.yml
  nfdapi/nfdcore/form_definitions/stream-animal-forms.yml
  nfdapi/nfdcore/form_definitions/wetland-animal-forms.yml
  nfdapi/nfdcore/formdefinitions.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
  nfdapi/nfdcore/views.py
  nfdapi/requirements.txt
Labels: in progress, pending review, review

#181 moved form fields around and fixed stringcombo issue
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/form_definitions/conifer-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fern-plant-forms.yml
  nfdapi/nfdcore/form_definitions/flowering-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fungus-forms.yml
  nfdapi/nfdcore/form_definitions/land-animal-forms.yml
  nfdapi/nfdcore/form_definitions/moss-forms.yml
  nfdapi/nfdcore/form_definitions/natural-area-forms.yml
  nfdapi/nfdcore/form_definitions/pond-lake-animal-forms.yml
  nfdapi/nfdcore/form_definitions/slimemold-forms.yml
  nfdapi/nfdcore/form_definitions/stream-animal-forms.yml
  nfdapi/nfdcore/form_definitions/wetland-animal-forms.yml
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#184 moved mushroom_group to the FungusDetails model
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/form_definitions/fungus-forms.yml
  nfdapi/nfdcore/migrations/0022_auto_20180220_1714.py
  nfdapi/nfdcore/models.py
Labels: in progress, pending review, review

#188 Implemented integration with ITIS and refactored Taxon model
  nfdapi/nfdapi/settings.py
  nfdapi/nfdapi/urls.py
  nfdapi/nfdcore/admin.py
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/form_definitions/conifer-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fern-plant-forms.yml
  nfdapi/nfdcore/form_definitions/flowering-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fungus-forms.yml
  nfdapi/nfdcore/form_definitions/land-animal-forms.yml
  nfdapi/nfdcore/form_definitions/moss-forms.yml
  nfdapi/nfdcore/form_definitions/natural-area-forms.yml
  nfdapi/nfdcore/form_definitions/pond-lake-animal-forms.yml
  nfdapi/nfdcore/form_definitions/slimemold-forms.yml
  nfdapi/nfdcore/form_definitions/stream-animal-forms.yml
  nfdapi/nfdcore/form_definitions/wetland-animal-forms.yml
  nfdapi/nfdcore/itis.py
  nfdapi/nfdcore/migrations/0023_taxon.py
  nfdapi/nfdcore/migrations/0024_auto_20180222_1556.py
  nfdapi/nfdcore/migrations/0025_taxon_kingdom.py
  nfdapi/nfdcore/migrations/0026_auto_20180222_1645.py
  nfdapi/nfdcore/migrations/0027_auto_20180223_1206.py
  nfdapi/nfdcore/migrations/0028_auto_20180226_1315.py
  nfdapi/nfdcore/migrations/0029_auto_20180226_1559.py
  nfdapi/nfdcore/migrations/0030_animallifestages.py
  nfdapi/nfdcore/migrations/0031_auto_20180226_1707.py
  nfdapi/nfdcore/migrations/0032_auto_20180226_1708.py
  nfdapi/nfdcore/migrations/0033_auto_20180226_2031.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
  nfdapi/nfdcore/permissions.py
  nfdapi/nfdcore/views.py
  nfdclient/js/api/naturalfeaturesdata.js
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.jsx
Labels: in progress, pending review, review

#192 fixed incorrect case of selected taxon rank
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#194 changed filter fields
  nfdapi/nfdcore/views.py
Labels: in progress, pending review, review

#195 added leap_concern to the Taxon model
  nfdapi/nfdcore/admin.py
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/migrations/0034_taxon_leap_concern.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#197 Closes #186
  nfdclient/config.json
Labels: in progress, pending review, review

#198 fixed serialization issue for kingdoms
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#200 Added watershed as an additional filter parameter
  nfdapi/nfdcore/views.py
Labels: in progress, pending review, review

#201 changed filter parameter to featuretypes instead of kingdoms
  nfdapi/nfdcore/views.py
Labels: in progress, pending review, review

#202 changed definition of some forms to stringcombo
  nfdapi/nfdcore/form_definitions/common-pages.yml
Labels: in progress, pending review, review

#204 I#139
  nfdclient/assets/themes/default/nfd.less
  nfdclient/js/actions/featuresearch.js
  nfdclient/js/api/naturalfeaturesdata.js
  nfdclient/js/components/naturalfeatures/DockedNaturalFeatures.jsx
  nfdclient/js/components/naturalfeatures/FilterPanel.jsx
  nfdclient/js/components/naturalfeatures/SelectFilter.jsx
  nfdclient/js/components/naturalfeatures/SpeciesSelector.jsx
  nfdclient/js/components/naturalfeatures/UpperRankfilter.jsx
  nfdclient/js/epics/featuresearch.js
  nfdclient/js/plugins/featuretypes/Animal.jsx
  nfdclient/js/plugins/featuretypes/Category.jsx
  nfdclient/js/plugins/featuretypes/Fungus.jsx
  nfdclient/js/plugins/featuretypes/NaturalArea.jsx
  nfdclient/js/plugins/featuretypes/Plant.jsx
  nfdclient/js/plugins/featuretypes/Slimemold.jsx
  nfdclient/js/plugins/featuretypes/index.js
  nfdclient/js/reducers/featuresearch.js
  nfdclient/js/utils/FilterUtils.js
  nfdclient/js/utils/nfdUtils.js
Labels: in progress, pending review, review

#205 added the lifestages tab and fixed issues uncovered during testing
  nfdapi/nfdcore/form_definitions/common-pages.yml
  nfdapi/nfdcore/form_definitions/conifer-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fern-plant-forms.yml
  nfdapi/nfdcore/form_definitions/flowering-plant-forms.yml
  nfdapi/nfdcore/form_definitions/moss-plant-forms.yml
  nfdapi/nfdcore/nfdserializers.py
  nfdapi/nfdcore/permissions.py
Labels: in progress, pending review, review

#199 turn all lifestages models into dict tables
  nfdapi/README.md
  nfdapi/nfdcore/initmodel.py
  nfdapi/nfdcore/models.py
Labels: in progress, pending review, review

#206 made slimemold lifestages details part of its details model
  nfdapi/nfdcore/form_definitions/slimemold-forms.yml
  nfdapi/nfdcore/migrations/0035_auto_20180228_1554.py
  nfdapi/nfdcore/migrations/0036_auto_20180228_1559.py
  nfdapi/nfdcore/models.py
  nfdapi/nfdcore/nfdserializers.py
Labels: in progress, pending review, review

#207 Colses #203 and fixed authentication
  nfdclient/js/actions/naturalfeatures.js
  nfdclient/js/app.jsx
  nfdclient/js/appConfig.js
  nfdclient/js/components/naturalfeatures/FeatureCard.jsx
  nfdclient/js/epics/featuresearch.js
  nfdclient/js/epics/naturalfeatures.js
  nfdclient/js/reducers/security.js
Labels: in progress, pending review, review

#208 removed duplicate plant_count from the forms
  nfdapi/nfdcore/form_definitions/conifer-plant-forms.yml
  nfdapi/nfdcore/form_definitions/fern-plant-forms.yml
  nfdapi/nfdcore/form_definitions/moss-plant-forms.yml
Labels: in progress, pending review, review
